# Generated by Django 6.0.3 on 2026-03-19 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_2m_max', models.FloatField(blank=True, null=True)),
                ('temperature_2m_min', models.FloatField(blank=True, null=True)),
                ('temperature_2m_mean', models.FloatField(blank=True, null=True)),
                ('apparent_temperature_max', models.FloatField(blank=True, null=True)),
                ('apparent_temperature_min', models.FloatField(blank=True, null=True)),
                ('apparent_temperature_mean', models.FloatField(blank=True, null=True)),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('precipitation_sum', models.FloatField(blank=True, null=True)),
                ('rain_sum', models.FloatField(blank=True, null=True)),
                ('snowfall_sum', models.FloatField(blank=True, default=0.0, null=True)),
                ('precipitation_hours', models.FloatField(blank=True, null=True)),
                ('wind_speed_10m_max', models.FloatField(blank=True, null=True)),
                ('wind_gusts_10m_max', models.FloatField(blank=True, null=True)),
                ('wind_direction_10m_dominant', models.FloatField(blank=True, null=True)),
                ('daylight_duration', models.FloatField(blank=True, null=True)),
                ('sunshine_duration', models.FloatField(blank=True, null=True)),
                ('shortwave_radiation_sum', models.FloatField(blank=True, null=True)),
                ('et0_fao_evapotranspiration', models.FloatField(blank=True, null=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_meteo', to='locations.ville')),
            ],
            options={
                'unique_together': {('ville', 'date')},
            },
        ),
    ]
