# Generated by Django 6.0.3 on 2026-03-19 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('niveau_severite', models.CharField(choices=[('modere', 'Modéré'), ('grave', 'Grave'), ('critique', 'Critique')], max_length=20)),
                ('message_fr', models.TextField()),
                ('message_en', models.TextField()),
                ('est_active', models.BooleanField(default=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='locations.ville')),
            ],
        ),
    ]
