# Generated by Django 6.0.3 on 2026-04-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerte',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='alerte',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='donnees_declencheur',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='duree_estimee',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alerte',
            name='recommandations_residents_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alerte',
            name='recommandations_residents_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alerte',
            name='recommandations_visiteurs_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alerte',
            name='recommandations_visiteurs_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alerte',
            name='source',
            field=models.CharField(choices=[('ml', 'Modèle ML'), ('admin', 'Administrateur')], default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='alerte',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('ignoree', 'Ignorée')], default='brouillon', max_length=20),
        ),
    ]
