# Generated by Django 6.0.3 on 2026-03-19 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualiteAir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cible', models.DateField()),
                ('valeur_pm25', models.FloatField()),
                ('indice_aqi', models.IntegerField()),
                ('categorie', models.CharField(choices=[('Bon', 'Bon (0-50)'), ('Modere', 'Modéré (51-100)'), ('Sensible', 'Sensible (101-150)'), ('Malsain', 'Malsain (151-200)'), ('Tres_malsain', 'Très malsain (201-300)'), ('Dangereux', 'Dangereux (300+)')], max_length=20)),
                ('est_prediction', models.BooleanField(default=False)),
                ('facteurs_aggravants', models.JSONField(blank=True, null=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualite_air', to='locations.ville')),
            ],
            options={
                'unique_together': {('ville', 'date_cible', 'est_prediction')},
            },
        ),
    ]
